version: '3.3'

services:
  nestjs:
    container_name: clothing_store_production_nestjs
    labels:
      - traefik.http.routers.nestjs.entrypoints=websecure
      - traefik.http.routers.nestjs.tls.certresolver=lets-encrypt

  traefik:
    image: traefik:v2.4
    container_name: clothing_store_production_traefik
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=backend"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.lets-encrypt.acme.email=${ACME_EMAIL:?Please set the ACME_EMAIL env variable}"
      - "--certificatesResolvers.lets-encrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
      # Uncomment to get Traefik dashboard
      # - "--entryPoints.dashboard.address=:8090"
      # - "--api.dashboard=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt

volumes:
  letsencrypt:

networks:
  backend:
