#THIS IS THE DB FOR TESTING
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: clothingstoredb
    ports:
    - "5432:5432"
