#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
node << END
const { Client } = require("pg")

const connectionData = {
  user: "${POSTGRES_USER}",
  host: "${POSTGRES_HOST}",
  database: "${POSTGRES_DB}",
  password: "${POSTGRES_PASSWORD}",
  port: "${POSTGRES_PORT}",
}
const client = new Client(connectionData)

client.connect().then(() => {
    process.exit(0)
}).catch(() => {
    process.exit(1)
})
END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
